/**
 * 20 high-potential blog topics for Europe & global markets.
 * Each entry drives internal linking clusters across services and industries.
 */
export const BLOG_CATALOG = [
  {
    slug: 'seo-trends-european-businesses-2026',
    title: 'SEO Trends for European Businesses in 2026',
    metaTitle: 'SEO Trends for European Businesses in 2026',
    category: 'SEO Strategy',
    cluster: 'International SEO',
    intent: 'Informational',
    primaryKeyword: 'SEO trends Europe 2026',
    serviceLinks: ['/services/seo', '/services/ai-seo', '/services/generative-engine-optimization'],
    industryLinks: ['/industries/realtor-seo', '/industries/dentist-seo', '/industries/hvac-seo', '/industries/automotive-seo', '/industries/wineries-seo'],
    relatedBlogSlugs: [
      'international-seo-guide-european-companies',
      'ai-seo-vs-traditional-seo-2026',
      'local-seo-checklist-multi-location-europe',
      'google-ai-overviews-changing-business-seo',
    ],
    image: '/images/blog/seo-trends-european-businesses-2026-hero.svg',
    datePublished: '2026-07-15',
  },
  {
    slug: 'ai-seo-vs-traditional-seo-2026',
    title: 'AI SEO vs Traditional SEO: Which Strategy Wins in 2026?',
    metaTitle: 'AI SEO vs Traditional SEO: Which Wins in 2026?',
    category: 'AI SEO',
    cluster: 'AI SEO',
    intent: 'Commercial',
    primaryKeyword: 'AI SEO vs traditional SEO',
    serviceLinks: ['/services/ai-seo', '/services/seo'],
    industryLinks: ['/industries/plastic-surgery-seo', '/industries/doctor-physician-seo'],
    relatedBlogSlugs: [
      'local-vs-national-vs-international-seo',
      'google-ai-overviews-changing-business-seo',
      'geo-generative-engine-optimization-guide',
    ],
    image: '/images/blog/ai-seo-vs-traditional-seo-2026-hero.svg',
    datePublished: '2026-07-18',
  },
  {
    slug: 'local-seo-checklist-multi-location-europe',
    title: 'Local SEO Checklist for Multi-Location Businesses in Europe',
    metaTitle: 'Local SEO Checklist for Multi-Location Europe',
    category: 'Local SEO',
    cluster: 'Local SEO',
    intent: 'Commercial',
    primaryKeyword: 'local SEO checklist Europe',
    serviceLinks: ['/services/local-seo-service', '/services/gbp-optimization'],
    industryLinks: ['/industries/realtor-seo', '/industries/dentist-seo', '/industries/hvac-seo', '/industries/automotive-seo', '/industries/wineries-seo'],
    relatedBlogSlugs: [
      'google-business-profile-optimization-guide',
      'local-vs-national-vs-international-seo',
      'seo-checklist-small-businesses-europe',
    ],
    image: '/images/blog/local-seo-checklist-multi-location-europe-hero.svg',
    datePublished: '2026-07-20',
  },
  {
    slug: 'google-ai-overviews-changing-business-seo',
    title: 'How Google AI Overviews Are Changing Business SEO',
    metaTitle: 'How Google AI Overviews Change Business SEO',
    category: 'AI Search',
    cluster: 'Generative Engine Optimization',
    intent: 'Informational',
    primaryKeyword: 'Google AI Overviews SEO',
    serviceLinks: ['/services/generative-engine-optimization', '/services/ai-seo'],
    industryLinks: ['/industries/plastic-surgery-seo', '/industries/personal-injury-seo'],
    relatedBlogSlugs: [
      'how-google-ai-overviews-are-changing-seo',
      'chatgpt-seo-ai-search-organic-traffic',
      'ai-seo-vs-traditional-seo-2026',
      'geo-generative-engine-optimization-guide',
    ],
    image: '/images/blog/google-ai-overviews-changing-business-seo-hero.svg',
    datePublished: '2026-07-22',
  },
  {
    slug: '100-seo-mistakes-costing-business-leads',
    title: '100 SEO Mistakes That Cost Businesses Thousands of Leads',
    metaTitle: '100 SEO Mistakes Costing Businesses Leads',
    category: 'SEO Audit',
    cluster: 'Technical SEO',
    intent: 'Informational',
    primaryKeyword: 'SEO mistakes costing leads',
    serviceLinks: ['/services/seo', '/services/seo'],
    industryLinks: ['/industries/dentist-seo', '/industries/realtor-seo', '/industries/hvac-seo'],
    image: '/images/blog/100-seo-mistakes-costing-business-leads-hero.svg',
    datePublished: '2026-07-25',
  },
  {
    slug: 'international-seo-guide-european-companies',
    title: 'Complete International SEO Guide for European Companies',
    metaTitle: 'International SEO Guide for European Companies',
    category: 'International SEO',
    cluster: 'International SEO',
    intent: 'Commercial',
    primaryKeyword: 'international SEO Europe',
    serviceLinks: ['/services/seo', '/services/content-marketing'],
    industryLinks: ['/industries/realtor-seo', '/industries/architect-seo'],
    relatedBlogSlugs: [
      'seo-trends-european-businesses-2026',
      'local-vs-national-vs-international-seo',
      'local-seo-checklist-multi-location-europe',
    ],
    image: '/images/blog/international-seo-guide-european-companies-hero.svg',
    datePublished: '2026-07-28',
  },
  {
    slug: 'seo-healthcare-businesses-europe',
    title: 'SEO for Healthcare Businesses: Best Practices in Europe',
    metaTitle: 'SEO for Healthcare Businesses in Europe',
    category: 'Healthcare SEO',
    cluster: 'Healthcare SEO',
    intent: 'Industry',
    primaryKeyword: 'healthcare SEO Europe',
    serviceLinks: ['/services/seo', '/services/content-marketing', '/services/online-reputation-management'],
    industryLinks: ['/industries/dentist-seo', '/industries/doctor-physician-seo', '/industries/plastic-surgery-seo'],
    image: '/images/blog/seo-healthcare-businesses-europe-hero.svg',
    datePublished: '2026-07-30',
  },
  {
    slug: 'seo-law-firms-complete-guide',
    title: 'SEO for Law Firms: Complete Guide',
    metaTitle: 'SEO for Law Firms: Complete Guide 2026',
    category: 'Legal SEO',
    cluster: 'Legal SEO',
    intent: 'Industry',
    primaryKeyword: 'law firm SEO',
    serviceLinks: ['/services/seo', '/services/content-marketing'],
    industryLinks: ['/industries/personal-injury-seo', '/industries/cpa-firm-seo'],
    image: '/images/blog/seo-law-firms-complete-guide-hero.svg',
    datePublished: '2026-08-01',
  },
  {
    slug: 'choose-best-seo-agency-europe',
    title: 'How to Choose the Best SEO Agency in Europe',
    metaTitle: 'How to Choose the Best SEO Agency in Europe',
    category: 'SEO Services',
    cluster: 'International SEO',
    intent: 'Commercial',
    primaryKeyword: 'best SEO agency Europe',
    serviceLinks: ['/services/seo', '/services/ai-seo'],
    industryLinks: ['/industries/realtor-seo', '/industries/dentist-seo'],
    image: '/images/blog/choose-best-seo-agency-europe-hero.svg',
    datePublished: '2026-08-03',
  },
  {
    slug: 'local-vs-national-vs-international-seo',
    title: 'Local SEO vs National SEO vs International SEO',
    metaTitle: 'Local vs National vs International SEO',
    category: 'SEO Strategy',
    cluster: 'Local SEO',
    intent: 'Comparison',
    primaryKeyword: 'local vs national vs international SEO',
    serviceLinks: ['/services/local-seo-service', '/services/seo'],
    industryLinks: ['/industries/hvac-seo', '/industries/realtor-seo'],
    image: '/images/blog/local-vs-national-vs-international-seo-hero.svg',
    datePublished: '2026-08-05',
  },
  {
    slug: 'google-business-profile-optimization-guide',
    title: 'Google Business Profile Optimization Guide',
    metaTitle: 'Google Business Profile Optimization Guide',
    category: 'Local SEO',
    cluster: 'Local SEO',
    intent: 'Commercial',
    primaryKeyword: 'Google Business Profile optimization',
    serviceLinks: ['/services/gbp-optimization', '/services/local-seo-service'],
    industryLinks: ['/industries/dentist-seo', '/industries/plumber-seo', '/industries/hvac-seo', '/industries/automotive-seo', '/industries/wineries-seo'],
    image: '/images/blog/google-business-profile-optimization-guide-hero.svg',
    datePublished: '2026-08-07',
  },
  {
    slug: 'complete-eeat-guide-business-websites',
    title: 'Complete EEAT Guide for Business Websites',
    metaTitle: 'Complete EEAT Guide for Business Websites',
    category: 'Content SEO',
    cluster: 'Technical SEO',
    intent: 'Informational',
    primaryKeyword: 'EEAT guide business websites',
    serviceLinks: ['/services/content-marketing', '/services/seo'],
    industryLinks: ['/industries/doctor-physician-seo', '/industries/plastic-surgery-seo'],
    relatedBlogSlugs: [
      'content-marketing-strategy-qualified-leads',
      'link-building-guide-2026',
      'seo-healthcare-businesses-europe',
    ],
    image: '/images/blog/complete-eeat-guide-business-websites-hero.svg',
    datePublished: '2026-08-09',
  },
  {
    slug: 'geo-generative-engine-optimization-guide',
    title: 'GEO (Generative Engine Optimization): Complete Guide',
    metaTitle: 'GEO Generative Engine Optimization Guide',
    category: 'GEO',
    cluster: 'Generative Engine Optimization',
    intent: 'Informational',
    primaryKeyword: 'generative engine optimization GEO',
    serviceLinks: ['/services/generative-engine-optimization', '/services/ai-seo'],
    industryLinks: ['/industries/plastic-surgery-seo', '/industries/realtor-seo'],
    relatedBlogSlugs: [
      'chatgpt-seo-ai-search-organic-traffic',
      'seo-law-firms-complete-guide',
      'google-ai-overviews-changing-business-seo',
    ],
    image: '/images/blog/geo-generative-engine-optimization-guide-hero.svg',
    datePublished: '2026-08-11',
  },
  {
    slug: 'chatgpt-seo-ai-search-organic-traffic',
    title: 'ChatGPT SEO: How AI Search Is Changing Organic Traffic',
    metaTitle: 'ChatGPT SEO: AI Search & Organic Traffic',
    category: 'AI SEO',
    cluster: 'Answer Engine Optimization',
    intent: 'Informational',
    primaryKeyword: 'ChatGPT SEO organic traffic',
    serviceLinks: ['/services/ai-seo', '/services/answer-engine-optimization'],
    industryLinks: ['/industries/dentist-seo', '/industries/personal-injury-seo'],
    relatedBlogSlugs: [
      'geo-generative-engine-optimization-guide',
      'google-ai-overviews-changing-business-seo',
      'what-is-ai-seo-why-business-needs-it',
    ],
    image: '/images/blog/chatgpt-seo-ai-search-organic-traffic-hero.svg',
    datePublished: '2026-08-13',
  },
  {
    slug: 'seo-roi-calculator-measure-success',
    title: 'SEO ROI Calculator: How to Measure SEO Success',
    metaTitle: 'SEO ROI Calculator: Measure SEO Success',
    category: 'SEO Analytics',
    cluster: 'Technical SEO',
    intent: 'Commercial',
    primaryKeyword: 'SEO ROI calculator',
    serviceLinks: ['/seo-packages', '/services/seo'],
    industryLinks: ['/industries/realtor-seo', '/industries/hvac-seo'],
    image: '/images/blog/seo-roi-calculator-measure-success-hero.svg',
    datePublished: '2026-08-15',
  },
  {
    slug: 'technical-seo-checklist-enterprise-websites',
    title: 'Technical SEO Checklist for Enterprise Websites',
    metaTitle: 'Technical SEO Checklist for Enterprise',
    category: 'Technical SEO',
    cluster: 'Technical SEO',
    intent: 'Informational',
    primaryKeyword: 'technical SEO checklist enterprise',
    serviceLinks: ['/services/seo', '/services/ai-seo'],
    industryLinks: ['/industries/architect-seo', '/industries/cpa-firm-seo'],
    image: '/images/blog/technical-seo-checklist-enterprise-websites-hero.svg',
    datePublished: '2026-08-17',
  },
  {
    slug: 'core-web-vitals-optimization-guide',
    title: 'Core Web Vitals Optimization Guide',
    metaTitle: 'Core Web Vitals Optimization Guide 2026',
    category: 'Web Performance',
    cluster: 'Technical SEO',
    intent: 'Informational',
    primaryKeyword: 'Core Web Vitals optimization',
    serviceLinks: ['/services/ui-ux-design', '/services/seo'],
    industryLinks: ['/industries/interior-designer-seo', '/industries/home-builder-and-remodeler-seo'],
    image: '/images/blog/core-web-vitals-optimization-guide-hero.svg',
    datePublished: '2026-08-19',
  },
  {
    slug: 'content-marketing-strategy-qualified-leads',
    title: 'Content Marketing Strategy That Generates Qualified Leads',
    metaTitle: 'Content Marketing Strategy for Qualified Leads',
    category: 'Content Marketing',
    cluster: 'Content Marketing',
    intent: 'Commercial',
    primaryKeyword: 'content marketing qualified leads',
    serviceLinks: ['/services/content-marketing', '/services/seo'],
    industryLinks: ['/industries/realtor-seo', '/industries/dentist-seo'],
    relatedBlogSlugs: [
      'complete-eeat-guide-business-websites',
      'link-building-guide-2026',
      'seo-roi-calculator-measure-success',
    ],
    image: '/images/blog/content-marketing-strategy-qualified-leads-hero.svg',
    datePublished: '2026-08-21',
  },
  {
    slug: 'link-building-guide-2026',
    title: 'Complete Link Building Guide for 2026',
    metaTitle: 'Link Building Guide for 2026',
    category: 'SEO Strategy',
    cluster: 'Technical SEO',
    intent: 'Informational',
    primaryKeyword: 'link building guide 2026',
    serviceLinks: ['/services/seo', '/services/content-marketing'],
    industryLinks: ['/industries/personal-injury-seo', '/industries/plastic-surgery-seo'],
    relatedBlogSlugs: [
      'complete-eeat-guide-business-websites',
      'content-marketing-strategy-qualified-leads',
    ],
    image: '/images/blog/link-building-guide-2026-hero.svg',
    datePublished: '2026-08-23',
  },
  {
    slug: 'seo-checklist-small-businesses-europe',
    title: 'SEO Checklist for Small Businesses in Europe',
    metaTitle: 'SEO Checklist for Small Businesses in Europe',
    category: 'Small Business SEO',
    cluster: 'Local SEO',
    intent: 'Commercial',
    primaryKeyword: 'SEO checklist small business Europe',
    serviceLinks: ['/services/small-business-seo', '/services/local-seo-service'],
    industryLinks: ['/industries/plumber-seo', '/industries/dentist-seo', '/industries/hvac-seo'],
    image: '/images/blog/seo-checklist-small-businesses-europe-hero.svg',
    datePublished: '2026-08-25',
  },
]

export const PREMIUM_BLOG_SLUGS = BLOG_CATALOG.map((b) => b.slug)

export function getBlogCatalogEntry(slug) {
  return BLOG_CATALOG.find((b) => b.slug === slug) || null
}
