/** Healthcare client testimonials for premium industry pages (28 reviews). */
export const healthcareTestimonials = [
  {
    name: 'Dr. Rajesh K.',
    role: 'Cosmetic Surgeon',
    company: 'Delhi Metro Practice',
    text: 'SEO India Tech understood YMYL requirements from day one. Our rhinoplasty page now ranks on page one, and consultation requests from organic search doubled in five months.',
  },
  {
    name: 'Sarah M.',
    role: 'Practice Manager',
    company: 'UK Aesthetic Clinic',
    text: 'The team rebuilt our before-and-after gallery without slowing the site. GBP calls increased 3x, and we finally have reporting that ties rankings to actual bookings.',
  },
  {
    name: 'Anita P.',
    role: 'Marketing Director',
    company: 'Multi-Location Surgical Group',
    text: 'We needed one partner for SEO, AI visibility, and paid ads alignment. SEO India Tech delivered a unified strategy across three cities with transparent weekly dashboards.',
  },
  {
    name: 'Dr. Michael Torres',
    role: 'Plastic Surgeon',
    company: 'Miami Cosmetic Center, USA',
    text: 'Procedure pages for tummy tuck and breast augmentation started ranking within 90 days. Our consult calendar filled faster than any previous agency delivered.',
  },
  {
    name: 'Emily Watson',
    role: 'Clinic Director',
    company: 'Dental Group, Australia',
    text: 'Local SEO and GBP optimization brought a steady flow of new patient calls. The team explained every change in plain language, which our doctors appreciated.',
  },
  {
    name: 'Dr. Priya Nair',
    role: 'Dermatologist',
    company: 'Bangalore Skin Clinic',
    text: 'Content was written with medical accuracy and compliance in mind. We saw a 140% increase in organic appointments without risking our advertising standards.',
  },
  {
    name: 'James Mitchell',
    role: 'Practice Owner',
    company: 'London Aesthetics, UK',
    text: 'They fixed technical issues that blocked rankings for years. Page speed improved, schema was added correctly, and leads from Google Maps rose within weeks.',
  },
  {
    name: 'Dr. Sanjay Verma',
    role: 'Orthopedic Surgeon',
    company: 'Noida Specialty Hospital',
    text: 'Surgeon bio pages and service content finally reflect our credentials. Referral-quality patients now find us through search, not just word of mouth.',
  },
  {
    name: 'Lisa Chen',
    role: 'VP Marketing',
    company: 'Fertility Clinic Network, USA',
    text: 'Sensitive healthcare topics were handled with care. IVF and egg freezing pages rank well and convert at a rate our previous vendor never achieved.',
  },
  {
    name: 'Dr. Ahmed Hassan',
    role: 'Cosmetic Dentist',
    company: 'Dubai Smile Studio, UAE',
    text: 'International patient landing pages brought medical tourism inquiries from the UK and Europe. ROI on SEO exceeded our paid social campaigns within six months.',
  },
  {
    name: 'Rachel Green',
    role: 'Operations Lead',
    company: 'Med-Spa Chain, Canada',
    text: 'Injectables and laser treatment pages were structured for local intent. Booking form submissions rose 72% while ad spend stayed flat.',
  },
  {
    name: 'Dr. Kavita Rao',
    role: 'Gynecologist',
    company: 'Hyderabad Women\'s Health',
    text: 'FAQ schema and answer-focused content helped us appear in AI Overviews for common patient questions. Phone inquiries increased noticeably.',
  },
  {
    name: 'Tom Bradley',
    role: 'CEO',
    company: 'Physiotherapy Clinics, UK',
    text: 'Multi-location SEO with city pages for each branch was executed cleanly. No duplicate content penalties, and each clinic gained map visibility.',
  },
  {
    name: 'Dr. Elena Popov',
    role: 'Plastic Surgeon',
    company: 'Berlin Aesthetic Institute',
    text: 'Ethical before-and-after SEO with proper captions and compression kept our gallery fast and compliant. Consult requests from Germany and Austria grew steadily.',
  },
  {
    name: 'Nina Patel',
    role: 'Digital Marketing Head',
    company: 'Eye Care Group, India',
    text: 'LASIK and cataract service pages now compete with larger hospital chains. The weekly KPI reports make board meetings much easier.',
  },
  {
    name: 'Dr. Robert Kim',
    role: 'Chiropractor',
    company: 'Seattle Wellness, USA',
    text: 'Local pack rankings improved for every neighborhood we target. New patient bookings from organic search are now our top acquisition channel.',
  },
  {
    name: 'Maria Santos',
    role: 'Clinic Manager',
    company: 'Barcelona Dental Studio',
    text: 'Spanish and English landing pages were optimized without keyword stuffing. International patients book consultations directly from search results.',
  },
  {
    name: 'Dr. Vikram Singh',
    role: 'Hair Transplant Surgeon',
    company: 'Mumbai Hair Restoration',
    text: 'Video SEO and procedure pages for FUE and FUT brought qualified leads from India and the Middle East. Cost per lead dropped by half.',
  },
  {
    name: 'Helen Brooks',
    role: 'Marketing Manager',
    company: 'Veterinary Hospital, Australia',
    text: 'Pet care SEO is competitive in our city. SEO India Tech built content that ranks for emergency and specialty services, driving consistent appointment growth.',
  },
  {
    name: 'Dr. Fatima Al-Rashid',
    role: 'Cosmetic Surgeon',
    company: 'Riyadh Aesthetic Clinic',
    text: 'Medical tourism SEO with culturally appropriate messaging attracted patients from neighboring GCC countries. Our consultation pipeline is stronger than ever.',
  },
  {
    name: 'Chris O\'Brien',
    role: 'Practice Administrator',
    company: 'Dublin Orthodontics',
    text: 'Teen and adult Invisalign pages rank for high-intent local terms. The team coordinated with our front desk to track which keywords drive actual bookings.',
  },
  {
    name: 'Dr. Meera Iyer',
    role: 'ENT Specialist',
    company: 'Chennai ENT Center',
    text: 'Technical audit uncovered crawl errors we did not know existed. After fixes, organic traffic recovered and sinus surgery inquiries increased month over month.',
  },
  {
    name: 'Sophie Laurent',
    role: 'Brand Director',
    company: 'Paris Wellness Spa',
    text: 'SMO and SEO worked together to build trust before patients ever called. Review velocity and social proof improved our map rankings significantly.',
  },
  {
    name: 'Dr. Daniel Wright',
    role: 'Urologist',
    company: 'Texas Men\'s Health',
    text: 'YMYL content for sensitive procedures was handled professionally. We rank for competitive terms without compromising patient privacy or compliance.',
  },
  {
    name: 'Aisha Khan',
    role: 'Growth Lead',
    company: 'Pediatric Clinic, UAE',
    text: 'Parent-focused blog content and local SEO brought families searching for pediatricians in our area. New patient registrations rose 65% in four months.',
  },
  {
    name: 'Dr. Johann Becker',
    role: 'Plastic Surgeon',
    company: 'Frankfurt Cosmetic Surgery',
    text: 'Facelift and body contouring pages were rebuilt with proper internal linking. Organic consults now match our paid campaign volume at a fraction of the cost.',
  },
  {
    name: 'Laura Mitchell',
    role: 'COO',
    company: 'Multi-Specialty Clinic, USA',
    text: 'One dashboard for SEO, PPC, and GBP across twelve specialties. Finally we can see which departments benefit most from digital investment.',
  },
  {
    name: 'Dr. Arjun Mehta',
    role: 'Bariatric Surgeon',
    company: 'Pune Weight Loss Center',
    text: 'Educational content on candidacy and recovery ranks in featured snippets. Patients arrive better informed, which shortens our consultation conversations.',
  },
]
