import {
  Shield,
  Search,
  MapPin,
  Sparkles,
  BarChart3,
  Users,
  FileText,
  User,
  Image,
  Cpu,
  Megaphone,
  Building2,
  Hospital,
  Globe,
  Layers,
  Rocket,
  BookOpen,
  ClipboardList,
  Code,
  FlaskConical,
  RefreshCw,
  TrendingUp,
  Star,
} from 'lucide-react'

const ICON_MAP = {
  shield: Shield,
  search: Search,
  map: MapPin,
  sparkles: Sparkles,
  chart: BarChart3,
  users: Users,
  file: FileText,
  user: User,
  image: Image,
  cpu: Cpu,
  megaphone: Megaphone,
  building: Building2,
  hospital: Hospital,
  globe: Globe,
  sparkle: Sparkles,
  layers: Layers,
  rocket: Rocket,
  book: BookOpen,
  clipboard: ClipboardList,
  code: Code,
  flask: FlaskConical,
  refresh: RefreshCw,
  trending: TrendingUp,
  'bar-chart': BarChart3,
  'map-pin': MapPin,
  star: Star,
}

export function PremiumIcon({ name, className = 'h-6 w-6' }) {
  const Icon = ICON_MAP[name] || Star
  return <Icon className={className} aria-hidden="true" />
}
