/** Homepage client testimonials - used by sliding carousel (23 total). */
export const homeTestimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    role: 'Director of Marketing',
    company: 'HealthTech SaaS, India',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    text: 'SEO INDIA TECH rebuilt our organic strategy in six months. Traffic climbed steadily and demo requests finally matched our paid spend - the transparency in reporting made all the difference.',
  },
  {
    id: 2,
    name: 'James Mitchell',
    role: 'Founder',
    company: 'UK Retail Brand',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    text: 'They connected SEO, Google Ads, and landing page CRO under one team. Our client base grew significantly and ROAS improved without us juggling three different vendors.',
  },
  {
    id: 3,
    name: 'Sarah Chen',
    role: 'VP Growth',
    company: 'B2B SaaS, USA',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    text: 'Weekly reporting is clear - rankings, pipeline, and spend in one dashboard. Profits increased as campaigns scaled. That level of accountability is rare in agency partnerships.',
  },
  {
    id: 4,
    name: 'David Okonkwo',
    role: 'CEO',
    company: 'E-commerce, Nigeria',
    avatar: 'https://randomuser.me/api/portraits/men/75.jpg',
    text: 'Our product pages finally rank for high-intent keywords. Organic revenue grew 89% in eight months and we cut dependency on marketplace fees.',
  },
  {
    id: 5,
    name: 'Emily Watson',
    role: 'Marketing Manager',
    company: 'Dental Clinic Group, Australia',
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    text: 'Local SEO for twelve clinic locations was a mess before SEO INDIA TECH. Map pack visibility improved across every city and new patient bookings rose 47%.',
  },
  {
    id: 6,
    name: 'Rajesh Kumar',
    role: 'Owner',
    company: 'HVAC Services, Texas',
    avatar: 'https://randomuser.me/api/portraits/men/61.jpg',
    text: 'Emergency service calls from Google jumped within three months. They built dedicated pages for each service area and our GBP profiles actually convert now.',
  },
  {
    id: 7,
    name: 'Anna Kowalski',
    role: 'Head of Digital',
    company: 'Luxury Real Estate, Poland',
    avatar: 'https://randomuser.me/api/portraits/women/55.jpg',
    text: 'International SEO for three languages was handled expertly. We rank in Warsaw, Berlin, and London for property searches that used to go only to local agencies.',
  },
  {
    id: 8,
    name: 'Michael Torres',
    role: 'COO',
    company: 'Logistics SaaS, Canada',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    text: 'AI SEO and content hubs positioned us in ChatGPT and Google AI Overviews for industry queries. Enterprise demo requests from organic search doubled.',
  },
  {
    id: 9,
    name: 'Lisa Nguyen',
    role: 'Brand Director',
    company: 'Cosmetics Brand, Singapore',
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    text: 'ORM and social strategy repaired our reputation after a product launch crisis. Search sentiment turned positive and sales recovered faster than we projected.',
  },
  {
    id: 10,
    name: 'Oliver Bennett',
    role: 'Founder',
    company: 'FinTech Startup, UK',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    text: 'From zero organic visibility to top-three rankings for competitive fintech keywords in under a year. Their technical SEO audit fixed issues our dev team missed for years.',
  },
  {
    id: 11,
    name: 'Maria Gonzalez',
    role: 'Practice Manager',
    company: 'Orthodontics Clinic, Florida',
    avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
    text: 'Invisalign and teen braces pages now rank above national chains in our metro. Consultation form fills increased 62% with no increase in ad spend.',
  },
  {
    id: 12,
    name: 'Ahmed Hassan',
    role: 'Managing Partner',
    company: 'Law Firm, UAE',
    avatar: 'https://randomuser.me/api/portraits/men/88.jpg',
    text: 'Personal injury and corporate law pages comply with bar advertising rules while still ranking. Qualified case inquiries from search grew month over month.',
  },
  {
    id: 13,
    name: 'Jennifer Park',
    role: 'E-commerce Director',
    company: 'Home Goods, California',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    text: 'E-commerce SEO across 2,400 SKUs was reorganized with proper taxonomy. Category pages drive 3x more revenue from organic than before the migration.',
  },
  {
    id: 14,
    name: 'Thomas Weber',
    role: 'CMO',
    company: 'Manufacturing B2B, Germany',
    avatar: 'https://randomuser.me/api/portraits/men/53.jpg',
    text: 'B2B lead generation through SEO replaced expensive trade-show dependency. Industrial buyers find us through technical content that engineers actually trust.',
  },
  {
    id: 15,
    name: 'Sophie Laurent',
    role: 'Owner',
    company: 'Boutique Hotel, France',
    avatar: 'https://randomuser.me/api/portraits/women/90.jpg',
    text: 'Direct booking revenue rose as OTA commission costs fell. Local and international travel SEO brought guests searching for our exact neighborhood experience.',
  },
  {
    id: 16,
    name: 'Chris Anderson',
    role: 'General Manager',
    company: 'Auto Dealership, Ohio',
    avatar: 'https://randomuser.me/api/portraits/men/41.jpg',
    text: 'Service lane SEO for oil changes and brake repair filled our bays. Map calls and service appointments from Google are now our top acquisition channel.',
  },
  {
    id: 17,
    name: 'Nisha Patel',
    role: 'Director of Operations',
    company: 'EdTech Platform, India',
    avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    text: 'Course landing pages and blog content rank for career-focused keywords. Student signups from organic search scaled without proportional ad budget increases.',
  },
  {
    id: 18,
    name: 'Robert Kim',
    role: 'Founder',
    company: 'SaaS Analytics, South Korea',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    text: 'GEO optimization got us cited in AI Overviews for analytics comparisons. Trial signups from AI-referred traffic are now tracked and growing weekly.',
  },
  {
    id: 19,
    name: 'Helen Brooks',
    role: 'Marketing Lead',
    company: 'Nonprofit, Ireland',
    avatar: 'https://randomuser.me/api/portraits/women/48.jpg',
    text: 'Grant awareness and donor acquisition improved through content SEO. We reach supporters searching for causes we serve - not just people who already know us.',
  },
  {
    id: 20,
    name: 'Vikram Singh',
    role: 'CEO',
    company: 'Construction Company, Delhi',
    avatar: 'https://randomuser.me/api/portraits/men/36.jpg',
    text: 'Commercial and residential project pages rank in NCR for high-ticket renovation searches. Project inquiry quality improved - fewer tire-kickers, more serious buyers.',
  },
  {
    id: 21,
    name: 'Caroline Reed',
    role: 'VP Marketing',
    company: 'Insurance Broker, New York',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    text: 'Compliance-friendly SEO content ranks for policy comparison queries. Lead cost per qualified application dropped 34% while volume increased.',
  },
  {
    id: 22,
    name: 'Daniel Osei',
    role: 'Growth Manager',
    company: 'Mobile App, Ghana',
    avatar: 'https://randomuser.me/api/portraits/men/29.jpg',
    text: 'App Store Optimization and ASO landing pages improved installs across West Africa. Organic discovery now competes with paid UA on efficiency metrics.',
  },
  {
    id: 23,
    name: 'Yuki Tanaka',
    role: 'Head of SEO',
    company: 'Travel Agency, Japan',
    avatar: 'https://randomuser.me/api/portraits/women/57.jpg',
    text: 'Multilingual SEO for tour packages brought bookings from English and Japanese searchers. Seasonal content calendars align with travel demand peaks perfectly.',
  },
]
